% MDPLOT  Plot a 2D electronic spectrum as a filled contour map.
%
%   MDPLOT(XDATA, YDATA, ZDATA, T2VAL) renders a 2D spectrum using a
%   diverging blue-white-red colormap, with a diagonal reference line
%   and axis labels in wavenumber units.
%
%   Inputs:
%     XDATA  - frequency axis vector for the excitation dimension omega_1 [cm^-1]
%     YDATA  - frequency axis vector for the detection dimension omega_3 [cm^-1]
%     ZDATA  - 2D spectral intensity matrix (should be normalized before passing)
%     T2VAL  - waiting time value T2 [fs], used as the plot title
%
%   Notes:
%     - Contours are drawn with a level step of 0.1 (input should be normalized to [-1, 1])
%     - A diagonal line (omega_1 = omega_3) is drawn for reference
%     - Colormap is generated by CMAP2D with 10 color levels
%
%   See also: CMAP2D, NORMDIM

function MDplot(xdata, ydata, zdata,t2val)

%	Author: Jonathan D. Schultz
%	Email: jonathanschultz2022@u.northwestern.edu
%	Last revision date: February 1st, 2021
%
%	Copyright: Jonathan D. Schultz, 2021

%   Please see readme file for information about this package

cmap = cmap2d(10);

% Create contour
contourf(xdata,ydata,zdata,'LineWidth',0.25,'LevelStep',0.1);
colormap(cmap)
hold on

% Create line
line('XData',[min(ydata) max(ydata)],'YData',[min(ydata) max(ydata)],'Linewidth',1.5);

% Create ylabel
ylabel('\omega_{3} (cm^{-1})');
% ylabel('\lambda_{3} (nm)');

% Create xlabel
xlabel('\omega_{1} (cm^{-1})');
% xlabel('\lambda_{1} (nm)');

% Create title
title(t2val);

box on
set(gca,'BoxStyle','full','CLim',[-1 1],'DataAspectRatio',[1 1 1],...
    'FontSize',18,'Layer','top');

xlim([min(xdata) max(xdata)])
ylim([min(ydata) max(ydata)])
